export const SEARCH_ACTIONS = {
  UPDATE_SEARCH_VALUE: 'UPDATE_SEARCH_VALUE',
  INCREMENT_PAGE_NUMBER: 'INCREMENT_PAGE_NUMBER',
  CLEAR_PAGE_NUMBER: 'CLEAR_PAGE_NUMBER'
}

export const GIF_DATA_ACTIONS = {
  SEARCH_GIFS: 'SEARCH_GIFS',
  APPEND_GIFS: 'APPEND_GIFS',
  FAV_GIF: 'FAVORITE_GIF',
  LOADING_START: 'LOADING_START',
  SEARCH_ERROR: 'SEARCH_ERROR'
}